server:
  port: 9090
  servlet:
    context-path: /api/user
  
  
  
  
logging:
  file:
    path: logs/
    
spring:
  application:
    name: user-service
    
    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shatru
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  
      
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  